services:
  synkronus:
    image: ghcr.io/opendataensemble/synkronus:latest
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      LOG_LEVEL: "info"
      DB_CONNECTION: "postgres://synkronus_user:strong_password@db:5432/synkronus?sslmode=disable" # create with ~/create_synk_db demo      
      JWT_SECRET: "rcN76PE4cYMYZ9D3iy71eBqHsZ4feddcdAF7Zlsfom0=" # Generate a new one with: openssl rand -base64 32
      ADMIN_USERNAME: "please_change_the_username"
      ADMIN_PASSWORD: "change_the_password_as_well"
      APP_BUNDLE_PATH: "/app/data/app-bundles"
      MAX_VERSIONS_KEPT: "2"
    expose:
      - "8080" # in case you want to place a proxy, eg. nginx, in front of synkronus
    volumes:
      - appdata:/app/data # if you mount directly on the host, remember to set 1000 to owner (sudo chown -R 1000:1000 ...)
    depends_on:
      - db
    restart: unless-stopped
    healthcheck: ## This can be removed when the synkronus image is updated to support HEAD requests for /health
      test: ["CMD", "wget", "-qO-", "--tries=1", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3    

  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: synkronus_user      
      POSTGRES_PASSWORD: strong_password # change this!
      POSTGRES_DB: synkronus
    volumes:
       - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synkronus_user -d synkronous"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  appdata:

